-- https://thenounproject.com/ambriganti/collection/laundry-symbols/?oq=laundry&cidx=2
INSERT INTO attribute (id, filename, description) VALUES (1, 'noun_88713_cc.png', 'Hand Wash');
INSERT INTO attribute (id, filename, description) VALUES (2, 'noun_88714_cc.png', 'Washing');
INSERT INTO attribute (id, filename, description) VALUES (3, 'noun_88715_cc.png', 'Bleaching Allowed');
INSERT INTO attribute (id, filename, description) VALUES (4, 'noun_88716_cc.png', 'Wash At Or Below 50°C');
INSERT INTO attribute (id, filename, description) VALUES (5, 'noun_88717_cc.png', 'Wash At Or Below 60°C');
INSERT INTO attribute (id, filename, description) VALUES (6, 'noun_88718_cc.png', 'Do Not Wash');
INSERT INTO attribute (id, filename, description) VALUES (7, 'noun_88719_cc.png', 'Do Not Bleach');
INSERT INTO attribute (id, filename, description) VALUES (8, 'noun_88720_cc.png', 'Do Not Bleach');
INSERT INTO attribute (id, filename, description) VALUES (9, 'noun_88721_cc.png', 'Non-Chlorine Bleach Only');
INSERT INTO attribute (id, filename, description) VALUES (10, 'noun_88722_cc.png', 'Line Dry In The Shade');
INSERT INTO attribute (id, filename, description) VALUES (11, 'noun_88723_cc.png', 'Drying');
INSERT INTO attribute (id, filename, description) VALUES (12, 'noun_88724_cc.png', 'Dry Flat');
INSERT INTO attribute (id, filename, description) VALUES (13, 'noun_88725_cc.png', 'Wash At Or Below 30°C');
INSERT INTO attribute (id, filename, description) VALUES (14, 'noun_88726_cc.png', 'Line Dry');
INSERT INTO attribute (id, filename, description) VALUES (15, 'noun_88727_cc.png', 'Drip Dry');
INSERT INTO attribute (id, filename, description) VALUES (16, 'noun_88728_cc.png', 'Dry In The Shade');
INSERT INTO attribute (id, filename, description) VALUES (17, 'noun_88729_cc.png', 'Wash At Or Below 40°C');
INSERT INTO attribute (id, filename, description) VALUES (18, 'noun_88730_cc.png', 'Drip Dry In Shade');
INSERT INTO attribute (id, filename, description) VALUES (19, 'noun_88731_cc.png', 'Iron At Low Temperature');
INSERT INTO attribute (id, filename, description) VALUES (20, 'noun_88732_cc.png', 'Ironing');
INSERT INTO attribute (id, filename, description) VALUES (21, 'noun_88733_cc.png', 'Dry Flat In Shade');
INSERT INTO attribute (id, filename, description) VALUES (22, 'noun_88734_cc.png', 'Do Not Iron');
INSERT INTO attribute (id, filename, description) VALUES (23, 'noun_88735_cc.png', 'Iron At High Temperature');
INSERT INTO attribute (id, filename, description) VALUES (24, 'noun_88736_cc.png', 'Iron At Medium Temperature');
INSERT INTO attribute (id, filename, description) VALUES (25, 'noun_88737_cc.png', 'Professional Wet Cleaning');
INSERT INTO attribute (id, filename, description) VALUES (26, 'noun_88738_cc.png', 'Tumble Drying');
INSERT INTO attribute (id, filename, description) VALUES (27, 'noun_88739_cc.png', 'Do Not Dry Clean');
INSERT INTO attribute (id, filename, description) VALUES (28, 'noun_88740_cc.png', 'Very Gentle Wet Cleaning');
INSERT INTO attribute (id, filename, description) VALUES (29, 'noun_88741_cc.png', 'Do Not Tumble Dry');
INSERT INTO attribute (id, filename, description) VALUES (30, 'noun_88742_cc.png', 'Tumble Drying At Low Temperature');
INSERT INTO attribute (id, filename, description) VALUES (31, 'noun_88743_cc.png', 'Professional Cleaning');
INSERT INTO attribute (id, filename, description) VALUES (32, 'noun_88744_cc.png', 'Tumble Drying');
INSERT INTO attribute (id, filename, description) VALUES (33, 'noun_88745_cc.png', 'Dry Clean');
INSERT INTO attribute (id, filename, description) VALUES (34, 'noun_88746_cc.png', 'Very Gentle Cleaning With PCE');
INSERT INTO attribute (id, filename, description) VALUES (35, 'noun_88747_cc.png', 'Gentle Cleaning With Hydrocarbon Solvents');
INSERT INTO attribute (id, filename, description) VALUES (36, 'noun_88748_cc.png', 'Gentle Wet Cleaning');
INSERT INTO attribute (id, filename, description) VALUES (37, 'noun_88749_cc.png', 'Gentle Cleaning With PCE');
INSERT INTO attribute (id, filename, description) VALUES (38, 'noun_88750_cc.png', 'Professional Wet Cleaning Is Not Allowed');
INSERT INTO attribute (id, filename, description) VALUES (39, 'noun_88751_cc.png', 'Very Gentle Cleaning With Hydrocarbon Solvents');
INSERT INTO attribute (id, filename, description) VALUES (40, 'noun_88752_cc.png', 'Dry Clean PCE Only');
